sudo: required
language: python
services:
    - docker
before_install:
    - docker pull ubuntu
install:
    - docker run -d --name opm_ubuntu ubuntu
before_script:
    - bash -c "echo \"hello, world one\""
script:
    - docker ps -a
    - bash -c "echo \"hello, world two\""
    - docker rm opm_ubuntu
